//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace BitcoinMarketLoader.Infrastructure.Dtos.CnbApi
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BaseResponse
    {

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CzeoniaDailyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("czeoniaDaily")]
        public CzeoniaRest CzeoniaDaily { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CzeoniaDailyYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<CzeoniaRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CzeoniaRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("rate")]
        public double? Rate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("volumeInCZKmio")]
        public int? VolumeInCZKmio { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ErrorResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("endPoint")]
        public string EndPoint { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("errorCode")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ErrorResponseErrorCode>))]
        public ErrorResponseErrorCode? ErrorCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("happenedAt")]
        public System.DateTimeOffset? HappenedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        public string MessageId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateDailyCurrencyMonthResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<ExRateSelectedRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateDailyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<ExRateDailyRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateDailyRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        public long? Amount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string Country { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currency")]
        public string Currency { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currencyCode")]
        public string CurrencyCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("order")]
        public int? Order { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rate")]
        public double? Rate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateDailyYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<ExRateYearRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateMonthlyAverageCurrencyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("averages")]
        public System.Collections.Generic.ICollection<ExRateMonthlyAverageRest> Averages { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateMonthlyAverageRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        public int? Amount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("average")]
        public double? Average { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currencyCode")]
        public string CurrencyCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("month")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ExRateMonthlyAverageRestMonth>))]
        public ExRateMonthlyAverageRestMonth? Month { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("year")]
        public int? Year { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateMonthlyAverageYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("averages")]
        public System.Collections.Generic.ICollection<ExRateMonthlyAverageRest> Averages { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateMonthlyCumulativeAveragesCurrencyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("averages")]
        public System.Collections.Generic.ICollection<ExRateMonthlyAverageRest> Averages { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateMonthlyCumulativeAveragesYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("averages")]
        public System.Collections.Generic.ICollection<ExRateMonthlyAverageRest> Averages { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateQuarterlyAveragesCurrencyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("averages")]
        public System.Collections.Generic.ICollection<ExRateMonthlyAverageRest> Averages { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateQuarterlyAveragesYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("averages")]
        public System.Collections.Generic.ICollection<ExRateMonthlyAverageRest> Averages { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateSelectedRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        public int? Amount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currencyCode")]
        public string CurrencyCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rate")]
        public double? Rate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExRateYearRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        public int? Amount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currencyCode")]
        public string CurrencyCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rate")]
        public double? Rate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FinmarketDailyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("operations")]
        public System.Collections.Generic.ICollection<FinmarketRest> Operations { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FinmarketDailyYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("operations")]
        public System.Collections.Generic.ICollection<FinmarketRest> Operations { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FinmarketRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("allotmentPercentage")]
        public double? AllotmentPercentage { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("averageAllotedRateInPercent")]
        public double? AverageAllotedRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("averageBidRateInPercent")]
        public double? AverageBidRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("liquidityImpact")]
        public string LiquidityImpact { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("marginalRateInPercent")]
        public double? MarginalRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maturityDate")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? MaturityDate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maximumAllotedRateInPercent")]
        public double? MaximumAllotedRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maximumBidRateInPercent")]
        public double? MaximumBidRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("minimumAllotedRateInPercent")]
        public double? MinimumAllotedRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("minimumBidRateInPercent")]
        public double? MinimumBidRateInPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("operationType")]
        public string OperationType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("settlementDate")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? SettlementDate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalAllotedVolumeInCZKbln")]
        public double? TotalAllotedVolumeInCZKbln { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalBidVolumeInCZKbln")]
        public double? TotalBidVolumeInCZKbln { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalNumberOfAllotedBids")]
        public int? TotalNumberOfAllotedBids { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalNumberOfBids")]
        public int? TotalNumberOfBids { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tradeDate")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? TradeDate { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FwdDailyRangeCurrencyPairMaturityResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("forwardPoints")]
        public System.Collections.Generic.ICollection<FwdRateRest> ForwardPoints { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FwdRateDailyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("forwardPoints")]
        public System.Collections.Generic.ICollection<FwdRateRest> ForwardPoints { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FwdRateRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("ccyPair")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FwdRateRestCcyPair>))]
        public FwdRateRestCcyPair? CcyPair { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("forwardPoints")]
        public double? ForwardPoints { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maturity")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FwdRateRestMaturity>))]
        public FwdRateRestMaturity? Maturity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FxRateDailyMonthResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<FxRateRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FxRateDailyRangeCurrencyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<FxRateRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FxRateDailyYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("rates")]
        public System.Collections.Generic.ICollection<FxRateRest> Rates { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FxRateRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        public int? Amount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string Country { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currency")]
        public string Currency { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currencyCode")]
        public string CurrencyCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("order")]
        public int? Order { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rate")]
        public double? Rate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PriborDailyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("pribs")]
        public System.Collections.Generic.ICollection<PriborRest> Pribs { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PriborDailyYearResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("pribs")]
        public System.Collections.Generic.ICollection<PriborRest> Pribs { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PriborDailyYearTermResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("pribs")]
        public System.Collections.Generic.ICollection<PriborRest> Pribs { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PriborRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("period")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<PriborRestPeriod>))]
        public PriborRestPeriod? Period { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pribid")]
        public double? Pribid { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pribor")]
        public double? Pribor { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("validFor")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ValidFor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SkdDailyResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("skds")]
        public System.Collections.Generic.ICollection<SkdRest> Skds { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SkdRest
    {

        [System.Text.Json.Serialization.JsonPropertyName("averagePriceToValue")]
        public double? AveragePriceToValue { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isin")]
        public string Isin { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("issueCode")]
        public string IssueCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("issueName")]
        public string IssueName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nominalValueCZK")]
        public string NominalValueCZK { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nominalValueOfSettlementCZK")]
        public double? NominalValueOfSettlementCZK { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("settlementDate")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? SettlementDate { get; set; }

    }

    /// <summary>
    /// Language enumeration; default value: CZ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Lang
    {

        [System.Runtime.Serialization.EnumMember(Value = @"CZ")]
        CZ = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"EN")]
        EN = 1,

    }

    /// <summary>
    /// Currency pair enumeration
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CurrencyPair
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ALL")]
        ALL = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"EUR_TO_CZK")]
        EUR_TO_CZK = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"USD_TO_CZK")]
        USD_TO_CZK = 2,

    }

    /// <summary>
    /// Maturity enumeration
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Maturity
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ALL")]
        ALL = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"SIX_MONTH")]
        SIX_MONTH = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"THREE_MONTH")]
        THREE_MONTH = 2,

    }

    /// <summary>
    /// Language enumeration; default value: CZ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Lang2
    {

        [System.Runtime.Serialization.EnumMember(Value = @"CZ")]
        CZ = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"EN")]
        EN = 1,

    }

    /// <summary>
    /// Language enumeration; default value: CZ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Lang3
    {

        [System.Runtime.Serialization.EnumMember(Value = @"CZ")]
        CZ = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"EN")]
        EN = 1,

    }

    /// <summary>
    /// Language enumeration; default value: CZ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Lang4
    {

        [System.Runtime.Serialization.EnumMember(Value = @"CZ")]
        CZ = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"EN")]
        EN = 1,

    }

    /// <summary>
    /// Period enumeration
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Period
    {

        [System.Runtime.Serialization.EnumMember(Value = @"NINE_MONTH")]
        NINE_MONTH = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_DAY")]
        ONE_DAY = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_MONTH")]
        ONE_MONTH = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_WEEK")]
        ONE_WEEK = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_YEAR")]
        ONE_YEAR = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"SIX_MONTH")]
        SIX_MONTH = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"THREE_MONTH")]
        THREE_MONTH = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"TWO_MONTH")]
        TWO_MONTH = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"TWO_WEEKS")]
        TWO_WEEKS = 8,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ErrorResponseErrorCode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"INTERNAL_SERVER_ERROR")]
        INTERNAL_SERVER_ERROR = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"VALIDATION_ERROR")]
        VALIDATION_ERROR = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ExRateMonthlyAverageRestMonth
    {

        [System.Runtime.Serialization.EnumMember(Value = @"APR")]
        APR = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"APR_TO_JUN")]
        APR_TO_JUN = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"AUG")]
        AUG = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"DEC")]
        DEC = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"FEB")]
        FEB = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN")]
        JAN = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_APR")]
        JAN_TO_APR = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_AUG")]
        JAN_TO_AUG = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_DEC")]
        JAN_TO_DEC = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_FEB")]
        JAN_TO_FEB = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_JUL")]
        JAN_TO_JUL = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_JUN")]
        JAN_TO_JUN = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_MAR")]
        JAN_TO_MAR = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_MAY")]
        JAN_TO_MAY = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_NOV")]
        JAN_TO_NOV = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_OCT")]
        JAN_TO_OCT = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"JAN_TO_SEP")]
        JAN_TO_SEP = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"JUL")]
        JUL = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"JUL_TO_SEP")]
        JUL_TO_SEP = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"JUN")]
        JUN = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"MAR")]
        MAR = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"MAY")]
        MAY = 21,

        [System.Runtime.Serialization.EnumMember(Value = @"NOV")]
        NOV = 22,

        [System.Runtime.Serialization.EnumMember(Value = @"OCT")]
        OCT = 23,

        [System.Runtime.Serialization.EnumMember(Value = @"OCT_TO_DEC")]
        OCT_TO_DEC = 24,

        [System.Runtime.Serialization.EnumMember(Value = @"SEP")]
        SEP = 25,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum FwdRateRestCcyPair
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ALL")]
        ALL = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"EUR_TO_CZK")]
        EUR_TO_CZK = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"USD_TO_CZK")]
        USD_TO_CZK = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum FwdRateRestMaturity
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ALL")]
        ALL = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"SIX_MONTH")]
        SIX_MONTH = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"THREE_MONTH")]
        THREE_MONTH = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PriborRestPeriod
    {

        [System.Runtime.Serialization.EnumMember(Value = @"NINE_MONTH")]
        NINE_MONTH = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_DAY")]
        ONE_DAY = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_MONTH")]
        ONE_MONTH = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_WEEK")]
        ONE_WEEK = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"ONE_YEAR")]
        ONE_YEAR = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"SIX_MONTH")]
        SIX_MONTH = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"THREE_MONTH")]
        THREE_MONTH = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"TWO_MONTH")]
        TWO_MONTH = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"TWO_WEEKS")]
        TWO_WEEKS = 8,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
    {
        public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTimeOffset.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765