// <auto-generated />
using System;
using BitcoinMarketLoader.Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitcoinMarketLoader.Infrastructure.Databases.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitcoinMarketLoader.Domain.Market.MarketCurrency", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("MarketCurrencies");
                });

            modelBuilder.Entity("BitcoinMarketLoader.Domain.Market.MarketTick", b =>
                {
                    b.Property<long>("Ccseq")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instrument")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Market")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("PriceFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("QuoteCurrencyId")
                        .HasColumnType("bigint");

                    b.HasKey("Ccseq");

                    b.HasIndex("BaseCurrencyId");

                    b.HasIndex("QuoteCurrencyId");

                    b.ToTable("MarketTicks");
                });

            modelBuilder.Entity("BitcoinMarketLoader.Domain.Market.TradeStatistics", b =>
                {
                    b.Property<long>("SourceTickCcseq")
                        .HasColumnType("bigint");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<decimal?>("HighPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("LowPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("OpenPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("PriceChange")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("PriceChangePercent")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("QuoteVolumeBuy")
                        .HasPrecision(22, 8)
                        .HasColumnType("decimal(22,8)");

                    b.Property<decimal?>("QuoteVolumeSell")
                        .HasPrecision(22, 8)
                        .HasColumnType("decimal(22,8)");

                    b.Property<decimal?>("QuoteVolumeTotal")
                        .HasPrecision(22, 8)
                        .HasColumnType("decimal(22,8)");

                    b.Property<decimal?>("QuoteVolumeUnknown")
                        .HasPrecision(22, 8)
                        .HasColumnType("decimal(22,8)");

                    b.Property<long?>("TotalBuys")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSells")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTrades")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalUnknownTrades")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("VolumeBuy")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("VolumeSell")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("VolumeTotal")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("VolumeUnknown")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("SourceTickCcseq", "Range");

                    b.ToTable("TradeStatistics");
                });

            modelBuilder.Entity("BitcoinMarketLoader.Domain.Market.MarketTick", b =>
                {
                    b.HasOne("BitcoinMarketLoader.Domain.Market.MarketCurrency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BitcoinMarketLoader.Domain.Market.MarketCurrency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.Order", "BestAsk", b1 =>
                        {
                            b1.Property<long>("MarketTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Price")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("BestAsk_Price");

                            b1.Property<decimal?>("Quantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("BestAsk_Quantity");

                            b1.Property<decimal?>("QuoteQuantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("BestAsk_QuoteQuantity");

                            b1.HasKey("MarketTickCcseq");

                            b1.ToTable("MarketTicks");

                            b1.WithOwner()
                                .HasForeignKey("MarketTickCcseq");

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "LastUpdateTimestamp", b2 =>
                                {
                                    b2.Property<long>("OrderMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestAsk_LastUpdate_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestAsk_LastUpdate_UnixSeconds");

                                    b2.HasKey("OrderMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderMarketTickCcseq");
                                });

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "PositionUpdateTimestamp", b2 =>
                                {
                                    b2.Property<long>("OrderMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestAsk_PositionUpdate_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestAsk_PositionUpdate_UnixSeconds");

                                    b2.HasKey("OrderMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderMarketTickCcseq");
                                });

                            b1.Navigation("LastUpdateTimestamp");

                            b1.Navigation("PositionUpdateTimestamp");
                        });

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.Order", "BestBid", b1 =>
                        {
                            b1.Property<long>("MarketTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Price")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("BestBid_Price");

                            b1.Property<decimal?>("Quantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("BestBid_Quantity");

                            b1.Property<decimal?>("QuoteQuantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("BestBid_QuoteQuantity");

                            b1.HasKey("MarketTickCcseq");

                            b1.ToTable("MarketTicks");

                            b1.WithOwner()
                                .HasForeignKey("MarketTickCcseq");

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "LastUpdateTimestamp", b2 =>
                                {
                                    b2.Property<long>("OrderMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestBid_LastUpdate_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestBid_LastUpdate_UnixSeconds");

                                    b2.HasKey("OrderMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderMarketTickCcseq");
                                });

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "PositionUpdateTimestamp", b2 =>
                                {
                                    b2.Property<long>("OrderMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestBid_PositionUpdate_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("BestBid_PositionUpdate_UnixSeconds");

                                    b2.HasKey("OrderMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderMarketTickCcseq");
                                });

                            b1.Navigation("LastUpdateTimestamp");

                            b1.Navigation("PositionUpdateTimestamp");
                        });

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.TradeDetails", "LastProcessedTrade", b1 =>
                        {
                            b1.Property<long>("MarketTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<long>("Ccseq")
                                .HasColumnType("bigint")
                                .HasColumnName("LastProcessedTrade_Ccseq");

                            b1.Property<decimal?>("Price")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("LastProcessedTrade_Price");

                            b1.Property<decimal?>("Quantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("LastProcessedTrade_Quantity");

                            b1.Property<decimal?>("QuoteQuantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("LastProcessedTrade_QuoteQuantity");

                            b1.Property<int?>("Side")
                                .HasColumnType("int")
                                .HasColumnName("LastProcessedTrade_Side");

                            b1.Property<string>("TradeId")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastProcessedTrade_Id");

                            b1.HasKey("MarketTickCcseq");

                            b1.ToTable("MarketTicks");

                            b1.WithOwner()
                                .HasForeignKey("MarketTickCcseq");

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "ReceivedTimestamp", b2 =>
                                {
                                    b2.Property<long>("TradeDetailsMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastProcessedTrade_ReceivedTimestamp_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastProcessedTrade_ReceivedTimestamp_UnixSeconds");

                                    b2.HasKey("TradeDetailsMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("TradeDetailsMarketTickCcseq");
                                });

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "Timestamp", b2 =>
                                {
                                    b2.Property<long>("TradeDetailsMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastProcessedTrade_Timestamp_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastProcessedTrade_Timestamp_UnixSeconds");

                                    b2.HasKey("TradeDetailsMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("TradeDetailsMarketTickCcseq");
                                });

                            b1.Navigation("ReceivedTimestamp");

                            b1.Navigation("Timestamp");
                        });

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.TradeDetails", "LastTrade", b1 =>
                        {
                            b1.Property<long>("MarketTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<long>("Ccseq")
                                .HasColumnType("bigint")
                                .HasColumnName("LastTrade_Ccseq");

                            b1.Property<decimal?>("Price")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("LastTrade_Price");

                            b1.Property<decimal?>("Quantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("LastTrade_Quantity");

                            b1.Property<decimal?>("QuoteQuantity")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("LastTrade_QuoteQuantity");

                            b1.Property<int?>("Side")
                                .HasColumnType("int")
                                .HasColumnName("LastTrade_Side");

                            b1.Property<string>("TradeId")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastTrade_Id");

                            b1.HasKey("MarketTickCcseq");

                            b1.ToTable("MarketTicks");

                            b1.WithOwner()
                                .HasForeignKey("MarketTickCcseq");

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "ReceivedTimestamp", b2 =>
                                {
                                    b2.Property<long>("TradeDetailsMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastTrade_ReceivedTimestamp_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastTrade_ReceivedTimestamp_UnixSeconds");

                                    b2.HasKey("TradeDetailsMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("TradeDetailsMarketTickCcseq");
                                });

                            b1.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "Timestamp", b2 =>
                                {
                                    b2.Property<long>("TradeDetailsMarketTickCcseq")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Nanoseconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastTrade_Timestamp_Nanoseconds");

                                    b2.Property<long>("UnixSeconds")
                                        .HasColumnType("bigint")
                                        .HasColumnName("LastTrade_Timestamp_UnixSeconds");

                                    b2.HasKey("TradeDetailsMarketTickCcseq");

                                    b2.ToTable("MarketTicks");

                                    b2.WithOwner()
                                        .HasForeignKey("TradeDetailsMarketTickCcseq");
                                });

                            b1.Navigation("ReceivedTimestamp");

                            b1.Navigation("Timestamp");
                        });

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "PriceUpdateTimestamp", b1 =>
                        {
                            b1.Property<long>("MarketTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<long>("Nanoseconds")
                                .HasColumnType("bigint")
                                .HasColumnName("PriceUpdateTimestamp_Nanoseconds");

                            b1.Property<long>("UnixSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("PriceUpdateTimestamp_UnixSeconds");

                            b1.HasKey("MarketTickCcseq");

                            b1.ToTable("MarketTicks");

                            b1.WithOwner()
                                .HasForeignKey("MarketTickCcseq");
                        });

                    b.Navigation("BaseCurrency");

                    b.Navigation("BestAsk")
                        .IsRequired();

                    b.Navigation("BestBid")
                        .IsRequired();

                    b.Navigation("LastProcessedTrade");

                    b.Navigation("LastTrade");

                    b.Navigation("PriceUpdateTimestamp");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("BitcoinMarketLoader.Domain.Market.TradeStatistics", b =>
                {
                    b.HasOne("BitcoinMarketLoader.Domain.Market.MarketTick", "SourceTick")
                        .WithMany("TradeStatistics")
                        .HasForeignKey("SourceTickCcseq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "FirstTradeTimestamp", b1 =>
                        {
                            b1.Property<long>("TradeStatisticsSourceTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<int>("TradeStatisticsRange")
                                .HasColumnType("int");

                            b1.Property<long>("Nanoseconds")
                                .HasColumnType("bigint")
                                .HasColumnName("FirstTradeTimestamp_Nanoseconds");

                            b1.Property<long>("UnixSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("FirstTradeTimestamp_UnixSeconds");

                            b1.HasKey("TradeStatisticsSourceTickCcseq", "TradeStatisticsRange");

                            b1.ToTable("TradeStatistics");

                            b1.WithOwner()
                                .HasForeignKey("TradeStatisticsSourceTickCcseq", "TradeStatisticsRange");
                        });

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "HighPriceTimestamp", b1 =>
                        {
                            b1.Property<long>("TradeStatisticsSourceTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<int>("TradeStatisticsRange")
                                .HasColumnType("int");

                            b1.Property<long>("Nanoseconds")
                                .HasColumnType("bigint")
                                .HasColumnName("HighPriceTimestamp_Nanoseconds");

                            b1.Property<long>("UnixSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("HighPriceTimestamp_UnixSeconds");

                            b1.HasKey("TradeStatisticsSourceTickCcseq", "TradeStatisticsRange");

                            b1.ToTable("TradeStatistics");

                            b1.WithOwner()
                                .HasForeignKey("TradeStatisticsSourceTickCcseq", "TradeStatisticsRange");
                        });

                    b.OwnsOne("BitcoinMarketLoader.Domain.Market.MarketTimestamp", "LowPriceTimestamp", b1 =>
                        {
                            b1.Property<long>("TradeStatisticsSourceTickCcseq")
                                .HasColumnType("bigint");

                            b1.Property<int>("TradeStatisticsRange")
                                .HasColumnType("int");

                            b1.Property<long>("Nanoseconds")
                                .HasColumnType("bigint")
                                .HasColumnName("LowPriceTimestamp_Nanoseconds");

                            b1.Property<long>("UnixSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("LowPriceTimestamp_UnixSeconds");

                            b1.HasKey("TradeStatisticsSourceTickCcseq", "TradeStatisticsRange");

                            b1.ToTable("TradeStatistics");

                            b1.WithOwner()
                                .HasForeignKey("TradeStatisticsSourceTickCcseq", "TradeStatisticsRange");
                        });

                    b.Navigation("FirstTradeTimestamp");

                    b.Navigation("HighPriceTimestamp");

                    b.Navigation("LowPriceTimestamp");

                    b.Navigation("SourceTick");
                });

            modelBuilder.Entity("BitcoinMarketLoader.Domain.Market.MarketTick", b =>
                {
                    b.Navigation("TradeStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
